import jsPDF from 'jspdf'

export interface PayslipData {
  employee: {
    name: string
    employee_id: string
    kra_pin?: string
  }
  month: string
  gross_salary: number
  basic_salary: number
  allowances_total: number
  overtime: number
  bonuses: number
  nssf_employee: number
  nssf_employer: number
  shif_employee: number
  shif_employer: number
  ahl_employee: number
  ahl_employer: number
  helb: number
  voluntary_deductions_total: number
  paye_after_relief: number
  total_deductions: number
  net_salary: number
  total_employer_cost: number
}

export interface RemittanceData {
  month: string
  employees: PayslipData[]
  totals: {
    nssfEmployee: number
    nssfEmployer: number
    nssfTotal: number
    shifEmployee: number
    shifEmployer: number
    shifTotal: number
    ahlEmployee: number
    ahlEmployer: number
    ahlTotal: number
    payeTotal: number
    totalNetPayroll: number
    totalEmployerCost: number
  }
}

export interface P9Data {
  employee: {
    name: string
    employee_id: string
    kra_pin: string
  }
  year: number
  gross_salary_total: number
  basic_salary_total: number
  allowances_total: number
  nssf_employee_total: number
  nssf_employer_total: number
  shif_employee_total: number
  shif_employer_total: number
  ahl_employee_total: number
  ahl_employer_total: number
  helb_total: number
  voluntary_deductions_total: number
  paye_total: number
  net_salary_total: number
  total_employer_cost: number
}

const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('en-KE', {
    style: 'currency',
    currency: 'KES',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount)
}

const formatDate = (dateString: string): string => {
  return new Date(dateString + '-01').toLocaleDateString('en-US', { 
    month: 'long', 
    year: 'numeric' 
  })
}

export const generatePayslipPDF = (data: PayslipData): void => {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 0, 0)
  doc.text('PEMWA AGENCY LIMITED', 105, 20, { align: 'center' })
  doc.setFontSize(10)
  doc.text('PAYROLL SYSTEM', 105, 27, { align: 'center' })
  doc.setFontSize(14)
  
  doc.setFontSize(16)
  doc.text('Monthly Payslip', 105, 30, { align: 'center' })
  
  // Employee Info
  doc.setFontSize(12)
  doc.text(`Employee: ${data.employee.name}`, 20, 50)
  doc.text(`ID: ${data.employee.employee_id}`, 20, 60)
  if (data.employee.kra_pin) {
    doc.text(`KRA PIN: ${data.employee.kra_pin}`, 20, 70)
  }
  doc.text(`Period: ${formatDate(data.month)}`, 120, 50)
  
  // Earnings Section
  doc.setFontSize(14)
  doc.text('EARNINGS', 20, 90)
  
  doc.setFontSize(10)
  doc.text('Basic Salary', 20, 100)
  doc.text(formatCurrency(data.basic_salary), 150, 100)
  
  doc.text('Allowances', 20, 110)
  doc.text(formatCurrency(data.allowances_total), 150, 110)
  
  doc.text('Overtime', 20, 120)
  doc.text(formatCurrency(data.overtime), 150, 120)
  
  doc.text('Bonuses', 20, 130)
  doc.text(formatCurrency(data.bonuses), 150, 130)
  
  doc.setFontSize(12)
  doc.text('Gross Salary', 20, 145)
  doc.text(formatCurrency(data.gross_salary), 150, 145)
  
  // Deductions Section
  doc.setFontSize(14)
  doc.text('DEDUCTIONS', 20, 165)
  
  doc.setFontSize(10)
  doc.text('NSSF (Employee)', 20, 175)
  doc.text(formatCurrency(data.nssf_employee), 150, 175)
  
  doc.text('SHIF (Employee)', 20, 185)
  doc.text(formatCurrency(data.shif_employee), 150, 185)
  
  doc.text('AHL (Employee)', 20, 195)
  doc.text(formatCurrency(data.ahl_employee), 150, 195)
  
  doc.text('PAYE', 20, 205)
  doc.text(formatCurrency(data.paye_after_relief), 150, 205)
  
  if (data.helb > 0) {
    doc.text('HELB', 20, 215)
    doc.text(formatCurrency(data.helb), 150, 215)
  }
  
  if (data.voluntary_deductions_total > 0) {
    doc.text('Voluntary Deductions', 20, 225)
    doc.text(formatCurrency(data.voluntary_deductions_total), 150, 225)
  }
  
  doc.setFontSize(12)
  doc.text('Total Deductions', 20, 240)
  doc.text(formatCurrency(data.total_deductions), 150, 240)
  
  // Net Salary
  doc.setFontSize(14)
  doc.text('NET SALARY', 20, 260)
  doc.text(formatCurrency(data.net_salary), 150, 260)
  
  // Employer Contributions
  doc.setFontSize(14)
  doc.text('EMPLOYER CONTRIBUTIONS', 20, 280)
  
  doc.setFontSize(10)
  doc.text('NSSF (Employer)', 20, 290)
  doc.text(formatCurrency(data.nssf_employer), 150, 290)
  
  doc.text('SHIF (Employer)', 20, 300)
  doc.text(formatCurrency(data.shif_employer), 150, 300)
  
  doc.text('AHL (Employer)', 20, 310)
  doc.text(formatCurrency(data.ahl_employer), 150, 310)
  
  doc.setFontSize(12)
  doc.text('Total Employer Cost', 20, 325)
  doc.text(formatCurrency(data.total_employer_cost), 150, 325)
  
  // Footer
  doc.setFontSize(8)
  doc.text('Generated by PEMWA AGENCY LIMITED', 105, 280, { align: 'center' })
  doc.text(new Date().toLocaleDateString(), 105, 285, { align: 'center' })
  
  // Download
  doc.save(`payslip-${data.employee.employee_id}-${data.month}.pdf`)
}

export const generateRemittancePDF = (data: RemittanceData): void => {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(20)
  doc.text('PEMWA AGENCY LIMITED', 105, 20, { align: 'center' })
  doc.setFontSize(10)
  doc.text('PAYROLL SYSTEM', 105, 27, { align: 'center' })
  doc.setFontSize(14)
  
  doc.setFontSize(16)
  doc.text('Government Remittance Summary', 105, 30, { align: 'center' })
  
  doc.setFontSize(12)
  doc.text(`Month: ${formatDate(data.month)}`, 105, 40, { align: 'center' })
  
  // Agency Totals
  doc.setFontSize(14)
  doc.text('AGENCY TOTALS', 20, 60)
  
  doc.setFontSize(10)
  doc.text('NSSF (Employee)', 20, 75)
  doc.text(formatCurrency(data.totals.nssfEmployee), 100, 75)
  
  doc.text('NSSF (Employer)', 20, 85)
  doc.text(formatCurrency(data.totals.nssfEmployer), 100, 85)
  
  doc.text('NSSF Total', 20, 95)
  doc.text(formatCurrency(data.totals.nssfTotal), 100, 95)
  
  doc.text('SHIF (Employee)', 20, 110)
  doc.text(formatCurrency(data.totals.shifEmployee), 100, 110)
  
  doc.text('SHIF (Employer)', 20, 120)
  doc.text(formatCurrency(data.totals.shifEmployer), 100, 120)
  
  doc.text('SHIF Total', 20, 130)
  doc.text(formatCurrency(data.totals.shifTotal), 100, 130)
  
  doc.text('AHL (Employee)', 20, 145)
  doc.text(formatCurrency(data.totals.ahlEmployee), 100, 145)
  
  doc.text('AHL (Employer)', 20, 155)
  doc.text(formatCurrency(data.totals.ahlEmployer), 100, 155)
  
  doc.text('AHL Total', 20, 165)
  doc.text(formatCurrency(data.totals.ahlTotal), 100, 165)
  
  doc.text('PAYE Total', 20, 180)
  doc.text(formatCurrency(data.totals.payeTotal), 100, 180)
  
  // WIBA removed
  
  // Summary
  doc.setFontSize(12)
  doc.text('Total Government Remittances', 20, 210)
  doc.text(formatCurrency(
    data.totals.nssfTotal + 
    data.totals.shifTotal + 
    data.totals.ahlTotal + 
    data.totals.payeTotal
  ), 100, 210)
  
  doc.text('Total Net Payroll', 20, 220)
  doc.text(formatCurrency(data.totals.totalNetPayroll), 100, 220)
  
  doc.text('Total Employer Cost', 20, 230)
  doc.text(formatCurrency(data.totals.totalEmployerCost), 100, 230)
  
  // Footer
  doc.setFontSize(8)
  doc.text('Generated by PEMWA AGENCY LIMITED', 105, 250, { align: 'center' })
  doc.text(new Date().toLocaleDateString(), 105, 255, { align: 'center' })
  
  // Download
  doc.save(`remittance-${data.month}.pdf`)
}

export const generateP9PDF = (data: P9Data): void => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  const left = margin
  const right = pageWidth - margin
  const amountX = right
  let y = margin + 10

  const hr = (yy: number) => {
    doc.setDrawColor(220)
    doc.line(left, yy, right, yy)
  }
  const row = (label: string, amount: number, showMonthly = false, dy = 8) => {
    y += dy
    doc.setFontSize(10)
    doc.text(label, left, y)
    doc.text(formatCurrency(amount), amountX, y, { align: 'right' })
    if (showMonthly) {
      doc.setTextColor(120)
      doc.setFontSize(8)
      const monthly = amount / 12
      doc.text(`(${formatCurrency(monthly)} × 12)`, amountX, y + 4, { align: 'right' })
      doc.setTextColor(0)
    }
  }

  // Header
  doc.setFontSize(18)
  doc.text('PEMWA AGENCY LIMITED', pageWidth / 2, y, { align: 'center' })
  doc.setFontSize(10)
  doc.text('PAYROLL SYSTEM', pageWidth / 2, y + 7, { align: 'center' })
  doc.setFontSize(14)
  y += 7
  doc.setFontSize(12)
  doc.text('P9 Form - Annual Tax Summary', pageWidth / 2, y, { align: 'center' })
  y += 8
  hr(y)

  // Employee Info
  y += 8
  doc.setFontSize(10)
  doc.text(`Employee: ${data.employee.name}`, left, y)
  doc.text(`Tax Year: ${data.year}`, right, y, { align: 'right' })
  y += 6
  doc.text(`ID: ${data.employee.employee_id}`, left, y)
  doc.text(`KRA PIN: ${data.employee.kra_pin}`, right, y, { align: 'right' })
  y += 6
  hr(y)

  // Annual Earnings
  y += 8
  doc.setFontSize(12)
  doc.text('ANNUAL EARNINGS', left, y)
  row('Basic Salary', data.basic_salary_total)
  row('Allowances', data.allowances_total)
  y += 2
  hr(y)
  y += 6
  doc.setFontSize(11)
  doc.text('Gross Salary', left, y)
  doc.text(formatCurrency(data.gross_salary_total), amountX, y, { align: 'right' })

  // Annual Deductions
  y += 10
  doc.setFontSize(12)
  doc.text('ANNUAL DEDUCTIONS', left, y)
  row('NSSF (Employee)', data.nssf_employee_total)
  row('SHIF (Employee)', data.shif_employee_total)
  row('AHL (Employee)', data.ahl_employee_total)
  row('PAYE', data.paye_total)
  if (data.helb_total > 0) row('HELB', data.helb_total)
  if (data.voluntary_deductions_total > 0) row('Voluntary Deductions', data.voluntary_deductions_total)
  y += 2
  hr(y)
  y += 6
  doc.setFontSize(11)
  doc.text('Total Deductions', left, y)
  const totalDeductions = data.nssf_employee_total + data.shif_employee_total + data.ahl_employee_total + data.paye_total + data.helb_total + data.voluntary_deductions_total
  doc.text(formatCurrency(totalDeductions), amountX, y, { align: 'right' })

  // Net Salary
  y += 10
  doc.setFontSize(12)
  doc.text('NET SALARY', left, y)
  row('Net Salary', data.net_salary_total, false, 6)

  // Employer Contributions
  y += 6
  hr(y)
  y += 8
  doc.setFontSize(12)
  doc.text('EMPLOYER CONTRIBUTIONS', left, y)
  row('NSSF (Employer)', data.nssf_employer_total)
  row('SHIF (Employer)', data.shif_employer_total)
  row('AHL (Employer)', data.ahl_employer_total)
  y += 2
  hr(y)
  y += 6
  doc.setFontSize(11)
  doc.text('Total Employer Cost', left, y)
  doc.text(formatCurrency(data.total_employer_cost), amountX, y, { align: 'right' })

  // Footer at the very bottom
  const footerY = pageHeight - 10
  doc.setFontSize(8)
  doc.text('Generated by PEMWA AGENCY LIMITED', pageWidth / 2, footerY - 3, { align: 'center' })
  doc.text(new Date().toLocaleDateString(), pageWidth / 2, footerY, { align: 'center' })

  doc.save(`p9-${data.employee.employee_id}-${data.year}.pdf`)
}
